language: python
sudo: true
install:
  - if [ "$WITH_OPT_DEPS" = "true" ] ; then pip install -vr requirements.txt; fi
  - pip install -v git+https://github.com/ProgVal/irctest.git
  - echo "y" | pip uninstall limnoria || true
# command to run tests, e.g. python setup.py test
script:
  - echo $TRAVIS_PYTHON_VERSION
  - python setup.py install
  - supybot-test test -v --plugins-dir=./plugins/ --no-network
  - if [ "$WITH_OPT_DEPS" = "true" ] -a [[ "$TRAVIS_PYTHON_VERSION" =~ ^3\.[4-9] ]] ; then python -m irctest irctest.controllers.limnoria; fi
notifications:
    email: false
matrix:
  include:
    - python: "3.4"
      env: WITH_OPT_DEPS=false
      dist: trusty
    - python: "3.5"
      env: WITH_OPT_DEPS=false
      dist: trusty
    - python: "3.6"
      env: WITH_OPT_DEPS=true
      dist: trusty

    - python: "3.7"
      env: WITH_OPT_DEPS=false
      dist: xenial
    - python: "3.7"
      env: WITH_OPT_DEPS=true
      dist: xenial
    - python: "3.8-dev"
      env: WITH_OPT_DEPS=true
      dist: xenial
    - python: "nightly"
      env: WITH_OPT_DEPS=true
      dist: xenial

    - python: "pypy3"
      env: WITH_OPT_DEPS=false
      dist: trusty

    - python: "nightly"
      env: WITH_OPT_DEPS=true
      dist: xenial

  allow_failures:
    - python: "pypy3"
      env: WITH_OPT_DEPS=true
      dist: xenial
