language: python
env:
  - PATH=$PATH:$HOME/.local/bin
python:
  - "3.2"
  - "2.7"
  - "2.6"
  - "2.5"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
# command to run tests, e.g. python setup.py test
script:
  - python setup.py install --user
  - supybot-test test
  - supybot-test --plugins-dir=plugins/
