language: python
sudo: true
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy"
  - "pypy-5.3.1" # default pypy3 doesn't work, see https://bitbucket.org/pypy/pypy/issues/2129/local-variable-val-referenced-before
env:
  - WITH_OPT_DEPS=true
  - WITH_OPT_DEPS=false
install:
  - if [ "$WITH_OPT_DEPS" = "true" ] ; then pip install -vr requirements.txt; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" =~ ^3\.[4-9] ]] ; then pip install -v git+https://github.com/ProgVal/irctest.git; fi
  - echo "y" | pip uninstall limnoria || true
# command to run tests, e.g. python setup.py test
script:
  - echo $TRAVIS_PYTHON_VERSION
  - python setup.py install
  - supybot-test test -v --plugins-dir=./plugins/ --no-network --disable-multiprocessing --exclude=./plugins/Scheduler --exclude=./plugins/Filter
  - if [[ "$TRAVIS_PYTHON_VERSION" =~ ^3\.[4-9] ]] ; then python -m irctest irctest.controllers.limnoria; fi
notifications:
    email: false
matrix:
  fast_finish: true
  allow_failures:
    - python: "nightly"
  exclude:
    - python: "2.6"
      env: WITH_OPT_DEPS=false
    - python: "3.2"
      env: WITH_OPT_DEPS=false
    - python: "3.3"
      env: WITH_OPT_DEPS=false
    - python: "3.4"
      env: WITH_OPT_DEPS=false
    - python: "3.5"
      env: WITH_OPT_DEPS=false
    - python: "nightly"
      env: WITH_OPT_DEPS=false
    - python: "pypy"
      env: WITH_OPT_DEPS=false
    - python: "pypy3.3-5.2-alpha1"
      env: WITH_OPT_DEPS=false
